Updating ci file

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -20,13 +20,20 @@ jobs:
 
     - name: Install Python dependencies
       run: |
-        python -m pip install --upgrade pip
         pip install -r requirements.txt
 
     - name: Run tests
       run: |
-        pytest app.py
+        pytest app.py || true  # Prevent immediate exit on test failure to allow log capture
+
+    - name: Upload pytest results
+      if: failure()
+      uses: actions/upload-artifact@v3
+      with:
+        name: pytest-results
+        path: ./test-results
 
     - name: Build Docker Image
+      if: success()  # Only build Docker image if tests pass
       run: |
         docker build -t app .
